### ISSUE TITLE
Iterate a repeating group

### ISSUE THREAD

**Issue by s6577t** [arthurlm/quickfix-rs#18]
If I want to iterate the entries in a repeating group, such as market data entries, currently the number of entries needs to be explicitly extracted:

```
                let msg: &Message = // ... assigned somehwere
                 ...
                let no: usize = msg
                    .get_field(field_id::NO_MD_ENTRIES)
                    .unwrap()
                    .parse()
                    .unwrap();
              
                for i in 1..=no {
                    let g = md_sfr.clone_group_no_md_entries(i).unwrap();
                    let r#type = g.get_md_entry_type();
                    let px = g.get_md_entry_px();
                    let sz = g.get_md_entry_size().to_string();
                    ...
                }
```
This is not at all unreasonable since it looks like the expected API from quickfix c++ but an iterator would be nice. Maybe a good way to implement this would in `quickfix-msg-gen`?

**Comment by arthurlm** [comment]
Hi

I just committed to update that should resolve the issue:

1. The first one add a getter for the group item count: https://github.com/arthurlm/quickfix-rs/commit/111c9be34aeec3aa60637fb65486a149cf93f29c
   So this should simplify accessing how many groups there is in the message.
2. The second one is the feature you requested: https://github.com/arthurlm/quickfix-rs/commit/29ed45045f4f3cd83da698cf90de546cf062495b

Can you give it a try without me releasing a new version 🙏 ? Give me a feedback on this 😁 ?

If everything works for you as expected, I can then make a new release then close this issue.
